name: Build Windows EXE

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller matplotlib numpy scipy control sympy pillow fpdf2

    - name: Compilar para EXE
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=icon2.ico TCC.py

    - name: Fazer upload do executável
      uses: actions/upload-artifact@v3
      with:
        name: Controladores-EXE
        path: dist/*.exe
