# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Build Windows Executable

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Baixa o código do seu repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Instala dependências (incluindo sympy)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller fpdf2 matplotlib control numpy scipy sympy

      # 4. Gera o executável
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name="Controladores" TCC.py

      # 5. Faz upload do .exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Executable
          path: dist/Controladores.exe
